fetch-dependencies:
	curl -SL https://github.com/adieuadieu/serverless-chrome/releases/download/v1.0.0-55/stable-headless-chromium-amazonlinux-2017-03.zip > bin/headless-chromium.zip
	curl -SL https://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip > bin/chromedriver.zip 

	
